name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: |
        echo $PWD

        REVISION=$(git rev-parse HEAD)

        echo $REVISION

        echo "Replacing plist objects"

        /usr/libexec/PlistBuddy \
            -c "delete :objects:F4CEA53E23C29C9E0086EB16:requirement:branch" \
            samples/SmoketestSPM.xcodeproj/project.pbxproj

        /usr/libexec/PlistBuddy \
            -c "add :objects:F4CEA53E23C29C9E0086EB16:requirement:revision string $REVISION" \
            samples/SmoketestSPM.xcodeproj/project.pbxproj

        /usr/libexec/PlistBuddy \
            -c "set :objects:F4CEA53E23C29C9E0086EB16:requirement:kind revision" \
            samples/SmoketestSPM.xcodeproj/project.pbxproj

        xcodebuild build -scheme samples/SmoketestSPM \
            -sdk iphonesimulator \
            -verbose
